GET /tv.remote.control.universal.com/cros2.txt HTTP/1.1
User-Agent: Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.031)
Host: dialog-4a78.kxcdn.com
Accept-Encoding: gzip
Connection: keep-alive

